# Create a course
PUT localhost:8030/courses/{{$uuid}}
Content-Type: application/json

{
  "name": "The best course",
  "duration": "5 hours"
}

###

# Create a user
PUT localhost:8030/users/{{$uuid}}
Content-Type: application/json

{
    "name": "John",
    "duration": "johnlemon@email.com"
}

###
